version: "3.3"

services:
  backend:
    image: harbor.sm-developer.dev/muict/our-moment-backend:latest
    container_name: our-moment-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - backend_uploads:/app/uploads

volumes:
  backend_uploads:
